# This configuration file is an example of a basic benchmark configuration
# Fill all keys before using it in a HoNCAML pipeline
# Keys which need values are the ones with a commend above

global:
  # Specify one of the following: [regression, classification]
  problem_type: classification

steps:
  data:
    extract:
      # Specify path of file containing input data
      filepath: .dataset.csv
      # *REQ*: Specify target column name
      target: Class

  benchmark:
    transform:
      tuner:
        tune_config:
          metric: f1_score
      metrics:
        - f1_score
    load:
      # Specify folder in which to store benchmark results
      path: .honcaml
