# This configuration file is an example of a basic configuration
# Fill all keys before using it in a HoNCAML pipeline
# Keys which need values are the ones with a commend above

global:
  # Specify one of the following: [regression, classification]
  problem_type:
  # Specify folder in which to store execution results
  metrics_folder:

steps:
  data:
    extract:
      # Specify path of file containing input data
      filepath:
      # Specify target column name
      target:

  model:
    transform:
    load:
      # Specify folder in which to store model object
      path:
