global:
  problem_type: classification
steps:
  data:
    extract:
      filepath: data/processed/Iris_train.csv
      features:
        - SepalLengthCm
        - SepalWidthCm
        - PetalLengthCm
        - PetalWidthCm
      target:
        - Species

  model:
    estimator_config:
      module: sklearn.ensemble.RandomForestClassifier
      hyper_parameters:
        n_estimators: 100

    transform:
      fit:
        cross_validation:
          strategy: k_fold
          n_splits: 2
          shuffle: True
          random_state: 90

    load:
      path: data/models/