global:
  problem_type: classification

steps:
  data:
    transform:
        encoding:
          OHE: True
    extract:
      filepath: data/classification_train.csv
      target: class

  model:
    transform:
      fit:
        estimator:
          module: torch
          params:
            epochs: 3
            layers:
              - module: torch.nn.Linear
                params:
                  out_features: 4
              - module: torch.nn.ReLU
              - module: torch.nn.Linear
                params:
                  out_features: 2
              - module: torch.nn.Dropout
              - module: torch.nn.Linear
            loader:
              batch_size: 5
              shuffle: True
            loss:
              module: torch.nn.CrossEntropyLoss
            optimizer:
              module: torch.optim.SGD
              params:
                lr: 0.001
                momentum: 0.9

    load:
      filepath: honcaml_models/torch_classification.sav
