global:
  problem_type: classification

steps:
  data:
    extract:
      filepath: data/classification_train.csv
      features:
        - variance
        - skewness
      target: class

  benchmark:
    transform:
      models:
        sklearn.ensemble.RandomForestClassifier:
          n_estimators:
            method: randint
            values: [ 2, 110 ]
          max_features:
            method: choice
            values:
              - sqrt
              - log2
              - 1 # It means 'auto'
        sklearn.neighbors.KNeighborsClassifier:
          n_neighbors:
            method: randint
            values: [ 1, 100 ]
          weights:
            method: choice
            values:
              - uniform
              - distance
        torch:
          epochs:
            method: randint
            values: [2, 5]
          layers:
            number_blocks: [3, 6]
            types:
              - Linear + ReLU
              - Dropout
            params:
              Dropout:
                p:
                  method: uniform
                  values: [0.4, 0.6]
          loader:
            batch_size:
              method: randint
              values: [20, 40]
            shuffle:
              method: choice
              values:
                - True
                - False
          loss:
            module: torch.nn.CrossEntropyLoss
            params:
          optimizer:
            method: choice
            values:
              - module: torch.optim.SGD
                params:
                  lr:
                    method: loguniform
                    values: [0.001, 0.01]
                  momentum:
                    method: uniform
                    values: [0.5, 1]
              - module: torch.optim.Adam
                params:
                  lr:
                    method: loguniform
                    values: [0.001, 0.1]
                  eps:
                    method: loguniform
                    values: [0.0000001, 0.00001]

      cross_validation:
        module: sklearn.model_selection.KFold
        params:
          n_splits: 2
          shuffle: True
          random_state: 90

      tuner:
        search_algorithm:
          module: ray.tune.search.optuna.OptunaSearch
          params:
        tune_config:
          num_samples: 5
          metric: roc_auc_score
          mode: max
        run_config:
          stop:
            training_iteration: 2
        scheduler:
          module: ray.tune.schedulers.HyperBandScheduler
          params:

      metrics:
        - accuracy_score
        - f1_score:
            average: macro

    load:
      save_best_config_params: True
      path: honcaml_reports

  model:
    transform:
      fit:
        cross_validation:
        module: sklearn.model_selection.KFold
        params:
          n_splits: 2
          shuffle: True
          random_state: 90

    load:
      filepath: honcaml_models/sklearn_classification_benchmark.sav
