regressors:
  sklearn.ensemble.RandomForestRegressor:
    search_space:
      # TODO: a list of hyper parameters to search as default
      n_estimators:
        method: randint
        value: [ 2, 100 ]


classifiers:
  sklearn.ensemble.RandomForestClassifier:
    search_space:
      # TODO: a list of hyper parameters to search as default
      n_estimators:
        method: randint
        value: [ 2, 100 ]

search_space_mapping:
  randint: tune.randint
  choice: tune.choice
  # Adding more functions here
