### Settings file
# This file is intended to contain specific project parameters

logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
  file: data/logs/{exec_name}.log

# Path of pipelines folder
pipeline_folder: config/pipelines

# Pipeline validation rules
pipeline_rules:

# Pipeline step settings (default settings for each pipeline step)
pipeline_steps:
  # Data Step settings
  data:
    library: src.data.data_step.DataStep

  # Model Step settings
  model:
    library: src.models.model_step.ModelStep

  # Benchmark Step settings
  benchmark:
    library: src.models.benchmark_step.BenchmarkStep
