### Settings file
# This file is intended to contain specific project parameters

logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
  file: data/logs/{exec_name}.log

# Path of pipelines folder
pipeline_folder: config/pipelines

# Pipeline validation rules
pipeline_rules:

# Step validation rules
step_rules:
  data:
    extract:
      filepath: 
        - required: True
      target: 
        - required: True
    transform:
      normalize:
        features:
          module: 
            - required: True
        target:
          module: 
            - required: True
    load:
      path: 
        - required: True
  model:
    extract:
      filepath: 
        - required: True
    transform:
      fit:
        cross_validation:
          strategy: 
            - required: True
      predict:
        path:
          - required: True
    load:
      path:
        - required: True
  benchmark:
    

# Pipeline steps settings (default settings for each pipeline steps)
pipeline_steps:
  # Data Step settings
  data:
    extract:
      filepath: data/raw/dataset.csv
      target:
        - target

    transform:
      normalize:
        features:
          module: sklearn.preprocessing.StandardScaler
        target:
          module: sklearn.preprocessing.StandardScaler

    # load:
    #  path: data/processed
    #  data: dataset.csv

  # Model Step settings
  model:
    extract:
      filepath: models/sklearn.regressor.20220819-122417.sav

    transform:
      fit:
        cross_validation:
          strategy: k_fold
          n_splits: 10
          shuffle: True
          random_state: 90
      predict:
        path: data/processed

    load:
      path: data/models/

  # Benchmark Step settings
  benchmark:
    extract:
      # read a previously saved learner
    transform:
      # List the models and hyperparameters to be tuned
      # Learner parameters

    load:
      # save the learner to disk and the results

# Available models settings
models:
  # List the models with their available hyperparameters to tune with their limits.