### Settings file
# This file is intended to contain specific project parameters

logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
  file: data/logs/{exec_name}.log

# Path of pipelines folder
pipeline_folder: config/pipelines

# Pipeline validation rules
pipeline_rules:

# Pipeline step settings (default settings for each pipeline step)
pipeline_steps:
  # Data Step settings
  data:
    # library: src.steps.data_step.DataStep
    extract:
      filepath: data/raw/dataset.csv
      target:
        - target1

    transform:

    # load:
    #  path: data/processed
    #  data: dataset.csv

  # Model Step settings
  model:
    library: src.steps.model_step.ModelStep
    model_config:
      library:
      hyperparameters:
    processes:
      extract:
        path: models/
        file: model.sav

      transform:
        fit:
        cross_validate:
        #predict:
        #evaluate:

      load:
        path: models/
        file: model.sav

  # Benchmark Step settings
  benchmark:
    library: src.steps.benchmark_step.BenchmarkStep
    processes:
      extract:
      transform:
      load:

# Available models settings
models:
  # List the models with their available hyperparameters to tune with their limits.