### Settings file
# This file is intended to contain specific project parameters

logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
  file: data/logs/{exec_name}.log

# Path of pipelines folder
pipeline_folder: config/pipelines

# Pipeline validation rules
pipeline_rules:

# Step validation rules
step_rules:
  data:
    extract:
      filepath: 
        - required: True
      target: 
        - required: True
    transform:
      normalize:
        features:
          module: 
            - required: True
        target:
          module: 
            - required: True
    load:
      path: 
        - required: True
  model:
    estimator_type: 
      - required: True
      - allowed: ['regressor', 'classifier']
    estimator_config:
      module: 
        - required: True
    extract:
      filepath: 
        - required: True
    transform:
      fit:
        cross_validation:
          strategy: 
            - required: True
      predict:    
  benchmark:
    

# Pipeline steps settings (default settings for each pipeline steps)
pipeline_steps:
  # Data Step settings
  data:
    extract:
      filepath: data/raw/dataset.csv
      target:
        - target

    transform:
      normalize:
        features:
          module: sklearn.preprocessing.StandardScaler
        target:
          module: sklearn.preprocessing.StandardScaler

    # load:
    #  path: data/processed
    #  data: dataset.csv

  # Model Step settings
  model:
    extract:
      filepath: models/sklearn.regressor.20220819-122417.sav

    transform:
      fit:
        cross_validation:
          strategy: k_fold
          n_splits: 10
          random_seed: 90
      predict:

    load:
      path: models/

  # Benchmark Step settings
  benchmark:
    extract:
    transform:
    load:

# Available models settings
models:
  # List the models with their available hyperparameters to tune with their limits.