### Settings file
# This file is intended to contain specific project parameters

logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
  file: data/logs/{exec_name}.log

# Path of pipelines folder
pipeline_folder: config/pipelines

# Pipeline validation rules
pipeline_rules:

# Pipeline step settings (default settings for each pipeline step)
pipeline_steps:
  # Data Step settings
  data:
    library: src.data.data_step.DataStep
    phases:
      extract:
        path: data/raw
        data: dataset.csv
        target: target

      transform:
        
      load:
        path: data/processed
        data: dataset.csv

  # Model Step settings
  model:
    library: src.models.model_step.ModelStep
    phases:
      extract:
        path: models/
        file: model.sav

      transform:
        train:
        #predict:
        evaluate:

      load:
        path: models/
        file: model.sav

  # Benchmark Step settings
  benchmark:
    library: src.models.benchmark_step.BenchmarkStep
    phases:
      extract:
      transform:
      load:

# Available models settings
models:
  # List the models with their available hyperparameters to tune with their limits.