### Settings file
# This file is intended to contain specific project parameters

logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
  file: data/logs/{exec_name}.log

# Path of pipelines folder
pipeline_folder: config/pipelines

# Pipeline validation rules
pipeline_rules:

# Pipeline steps settings (default settings for each pipeline steps)
pipeline_steps:
  # Data Step settings
  data:
    extract:
      filepath: data/raw/dataset.csv
      target:
        - target

    transform:

    # load:
    #  path: data/processed
    #  data: dataset.csv

  # Model Step settings
  model:
    extract:
      filepath: models/regressor.20220819-122417.sav

    transform:
      fit:
        cross_validate:
          strategy: k_fold
          n_splits: 10
          random_seed: 90
      predict:

    load:
      path: models/

  # Benchmark Step settings
  benchmark:
    extract:
    transform:
    load:

# Available models settings
models:
  # List the models with their available hyperparameters to tune with their limits.