global:
  problem_type: classification

steps:
  data:
    extract:
      filepath: data/processed/bank_test.csv

  model:
    extract:
      filepath: data/models/mymodel.sav
    transform:
      predict:
        path: reports
