global:
  problem_type: classification

steps:
  data:
    extract:
      filepath: data/processed/bank_train.csv
      target:
        - 'class'

  model:
    transform:
      fit:
        estimator:
          module: sklearn.ensemble.RandomForestClassifier
          params:
            n_estimators: 100          
        cross_validation:
          module: sklearn.model_selection.KFold
          params:
            n_splits: 2
            shuffle: True
            random_state: 90

    load:
      path: data/models
    
    save:
      save_name: mymodel

