global:
  problem_type: classification

steps:
  data:
    extract:
      filepath: data/processed/bank_test.csv

  model:
    extract:
      filepath:
    transform:
      predict:
        path: honcaml_reports
