global:
  problem_type: classification

logging:
  level: DEBUG

steps:
  data:
    extract:
      filepath: data/processed/bank_test.csv
      target: class

  model:
    extract:
      filepath: data/models/sklearn.20231116-133036.sav
    transform:
      predict:
        path: reports
