global:
  problem_type: classification

steps:
  data:
    extract:
      filepath: data/processed/bank_train.csv
      features:
        - variance
        - skewness
      target: class
        
  benchmark:            
    transform:
      models:
        torch:
          epochs:
            method: randint
            values: [2, 5]
          layers:
            number_blocks: [3, 6]
            types:
              - Linear + ReLU
              - Dropout
            params:
              Dropout:
                p: 
                  method: uniform
                  values: [0.4, 0.6]
          loader:
            batch_size:
              method: randint
              values: [20, 40]
            shuffle:
              method: choice
              values:
                - True
                - False
          loss:
            module: torch.nn.CrossEntropyLoss
            params:
          optimizer:
            method: choice
            values:
              - module: torch.optim.SGD
                params:
                  lr:
                    method: loguniform
                    values: [0.001, 0.01]
                  momentum:
                    method: uniform
                    values: [0.5, 1]
              - module: torch.optim.Adam
                params:
                  lr:
                    method: loguniform
                    values: [0.001, 0.1]
                  eps:
                    method: loguniform
                    values: [0.0000001, 0.00001]
      metrics: f1_score
    load:
      path: data/models
