global:
  problem_type: classification

steps:
  data:
    extract:
      filepath: data/processed/bank_test.csv

  model:
    extract:
      filepath: data/models/
    transform:
      predict:
        estimator:
          params:
            loader:
              batch_size: 20
              shuffle: True
        path: reports
