global:
  problem_type: classification

steps:
  data:
    extract:
      filepath: data/processed/bank_test.csv
      target: class

  model:
    extract:
      filepath: data/models/torch_classification.sav
    transform:
      predict:
        estimator:
          params:
            loader:
              batch_size: 20
              shuffle: True
        path: reports
