global:
  problem_type: classification
  metrics_folder: honcaml_reports
steps:
  data:
    extract:
      filepath: data/processed/bank_test.csv

  model:
    extract:
      filepath: data/models/sklearn.20230524-145140.sav
    transform:
      predict:
        path: data/predictions
