global:
  problem_type: classification
steps:
  data:
    extract:
      filepath: data/processed/sonar_test.csv

  model:
    extract:
      filepath: data/models/sklearn.20221025-124228.sav
    transform:
      predict:
        path: data/predictions