global:
  problem_type: classification
steps:
  data:
    extract:
      filepath: data/processed/sonar_train.csv
      target:
        - '60'

  model:
    estimator_config:
      module: sklearn.ensemble.RandomForestClassifier
      hyper_parameters:
        n_estimators: 100

    transform:
      fit:
        cross_validation:
          strategy: k_fold
          n_splits: 2
          shuffle: True
          random_state: 90

    load:
      path: data/models/